### ISSUE TITLE
Flox-lib is archived and deprecated

### ISSUE THREAD

**Issue by NoPlagiarism** [MinYn/flow-launcher-notion-plugin#1]
https://github.com/Garulf/Flox is archived in favor of https://github.com/garulf/pyflowlauncher

One of the reasons: [flox was created to support both Flow Launcher and legacy Wox. pyFlowLauncher is FL-only based plugin](https://www.github.com/Flow-Launcher/Flow.Launcher/issues/1877#issuecomment-1868640602)

**Comment by MinYn** [comment]
@NoPlagiarism Okay, I'll reflect this issue in the next update version.

**Comment by MinYn** [comment]
PR #2 Resolved
